{{- if .Values.service.create -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.instana.agent.name }}-svc
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: LoadBalancer
  ports:
  - port: 42699
    targetPort: 42699
  selector:
    app: {{ .Values.instana.agent.name }}
{{- end -}}
