image:
  name: instana/agent
  tag: latest
  pullPolicy: IfNotPresent

rbac:
  create: true

instana:
  zone: k8s-cluster-name
  leaderElectorPort: 42655
  agent:
    #key: your-key
    name: instana-agent
    endpoint:
      host: saas-us-west-2.instana.io
      port: 443
  azure:
    enabled: false
    # subscription_id: your subscription id
    # tenant_id: your tenant id
    # sp_id: your service principal id
    # sp_secret: your service principal secret

## Annotations to be added to pods
podAnnotations: {}
