apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "instana-agent.baseName" . }}-configuration
  labels:
    {{- include "instana-agent.helmChartLabels" . | nindent 4 }}
data:
  logging.properties: |
    ################################################################################
    #
    #    Config file shipped by Apache Karaf under ASF license modified by Instana.
    #
    ################################################################################

    ################################################################################
    #
    #    Licensed to the Apache Software Foundation (ASF) under one or more
    #    contributor license agreements.  See the NOTICE file distributed with
    #    this work for additional information regarding copyright ownership.
    #    The ASF licenses this file to You under the Apache License, Version 2.0
    #    (the "License"); you may not use this file except in compliance with
    #    the License.  You may obtain a copy of the License at
    #
    #       http://www.apache.org/licenses/LICENSE-2.0
    #
    #    Unless required by applicable law or agreed to in writing, software
    #    distributed under the License is distributed on an "AS IS" BASIS,
    #    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    #    See the License for the specific language governing permissions and
    #    limitations under the License.
    #
    ################################################################################

    # Configuration of the Instana logger. Changes will be hot-reloaded.
    log4j2.logger.instana.name = com.instana
    log4j2.logger.instana.level = DEBUG

    # Root logger - Only change on request by support.
    log4j2.rootLogger.level = DEBUG
    log4j2.rootLogger.appenderRef.RollingFile.ref = RollingFile
    log4j2.rootLogger.appenderRef.PaxOsgi.ref = PaxOsgi
    #log4j2.rootLogger.appenderRef.Console.ref = Console
    #log4j2.rootLogger.appenderRef.Syslog.ref = Syslog
    #log4j2.rootLogger.appenderRef.Syslog.level = ERROR

    # Common pattern layout for appenders
    log4j2.pattern = %d{yyyy-MM-dd'T'HH:mm:ss.SSSZZZZ} | %-5.5p | %-32.32t | %-16.16c{1} | %X{bundle.name} - %X{bundle.version} | %m%n

    # Appenders configuration

    # Console appender not used by default
    log4j2.appender.console.type = Console
    log4j2.appender.console.name = Console
    log4j2.appender.console.layout.type = PatternLayout
    log4j2.appender.console.layout.pattern = ${log4j2.pattern}

    # Rolling file appender
    log4j2.appender.rolling.type = RollingFile
    log4j2.appender.rolling.name = RollingFile
    log4j2.appender.rolling.fileName = ${karaf.data}/log/agent.log
    log4j2.appender.rolling.filePattern = ${karaf.data}/log/agent.log.%i
    log4j2.appender.rolling.append = true
    log4j2.appender.rolling.layout.type = PatternLayout
    log4j2.appender.rolling.layout.pattern = ${log4j2.pattern}
    log4j2.appender.rolling.policies.type = Policies
    log4j2.appender.rolling.policies.size.type = SizeBasedTriggeringPolicy
    log4j2.appender.rolling.policies.size.size = 2MB

    # OSGi appender
    log4j2.appender.osgi.type = PaxOsgi
    log4j2.appender.osgi.name = PaxOsgi
    log4j2.appender.osgi.filter = *

    # Syslog appender
    log4j2.appender.syslog.type=Syslog
    log4j2.appender.syslog.name=Syslog
    log4j2.appender.syslog.facility=SYSLOG
    log4j2.appender.syslog.host=localhost
    log4j2.appender.syslog.port=514
    log4j2.appender.syslog.protocol=UDP
  configuration.yaml: |
    # Manual a-priori configuration. Configuration will be only used when the sensor
    # is actually installed by the agent.
    # The commented out example values represent example configuration and are not
    # necessarily defaults. Defaults are usually 'absent' or mentioned separately.
    # Changes are hot reloaded unless otherwise mentioned.

    # It is possible to create files called 'configuration-abc.yaml' which are
    # merged with this file in file system order. So 'configuration-cde.yaml' comes
    # after 'configuration-abc.yaml'. Only nested structures are merged, values are
    # overwritten by subsequent configurations.

    # Secrets
    # To filter sensitive data from collection by the agent, all sensors respect
    # the following secrets configuration. If a key collected by a sensor matches
    # an entry from the list, the value is redacted.
    #com.instana.secrets:
    #  matcher: 'contains-ignore-case' # 'contains-ignore-case', 'contains', 'regex'
    #  list:
    #    - 'key'
    #    - 'password'
    #    - 'secret'

    # Host
    #com.instana.plugin.host:
    #  tags:
    #    - 'dev'
    #    - 'app1'

    # Hardware & Zone
    #com.instana.plugin.generic.hardware:
    #  enabled: true # disabled by default
    #  availability-zone: 'zone'
